name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Linux:
    uses: ./.github/workflows/build-linux.yml

  Windows:
    uses: ./.github/workflows/build-windows.yml

  macOS:
    uses: ./.github/workflows/build-macos.yml

  Other:
    uses: ./.github/workflows/build-other.yml
