name: FreeBSD builds

on:
  workflow_call:

jobs:
  build-sdl2-freebsd:
    name: Build (SDL2 ${{ matrix.arch }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            sysroot_arch: amd64
            target_triple: x86_64-freebsd.14.0
          - arch: i386
            target_triple: x86-freebsd.14.0
          - arch: aarch64
            target_triple: aarch64-freebsd.14.0
          - arch: riscv
            target_triple: riscv64-freebsd.14.0
            cflags: "-mcpu=baseline_rv64 -Xclang -target-feature -Xclang +zihintpause"
            cxxflags: "-mcpu=baseline_rv64 -Xclang -target-feature -Xclang +zihintpause"
    env:
      CC: "zig cc"
      CXX: "zig c++"
      CFLAGS: ${{ matrix.cflags }}
      CXXFLAGS: ${{ matrix.cxxflags }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Checkout SDL 2.24.x
        uses: actions/checkout@v7
        with:
          repository: libsdl-org/SDL
          ref: release-2.24.x
          path: vendor/SDL2

      - name: Build SDL2 from source
        run: |
          cmake -S vendor/SDL2 -B vendor/SDL2/build -G Ninja \
            -DCMAKE_SYSTEM_NAME=FreeBSD \
            -DCMAKE_SYSTEM_VERSION="14.0" \
            -DCMAKE_AR="${{ github.workspace }}/artifacts/zig-ar" \
            -DCMAKE_RANLIB="${{ github.workspace }}/artifacts/zig-ranlib" \
            -DCMAKE_C_COMPILER_AR="${{ github.workspace }}/artifacts/zig-ar" \
            -DCMAKE_CXX_COMPILER_AR="${{ github.workspace }}/artifacts/zig-ar" \
            -DCMAKE_C_COMPILER_RANLIB="${{ github.workspace }}/artifacts/zig-ranlib" \
            -DCMAKE_CXX_COMPILER_RANLIB="${{ github.workspace }}/artifacts/zig-ranlib" \
            -DCMAKE_C_COMPILER_TARGET=${{ matrix.target_triple }} \
            -DCMAKE_CXX_COMPILER_TARGET=${{ matrix.target_triple }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/vendor/SDL2/install" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POLICY_DEFAULT_CMP0069=NEW \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
            -DSDL_SHARED=OFF \
            -DSDL_STATIC=ON \
            -DSDL_TESTS=OFF \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          cmake --build vendor/SDL2/build
          cmake --install vendor/SDL2/build

      - name: Configure and build Butterscotch
        env:
          PKG_CONFIG_PATH: "${{ github.workspace }}/vendor/SDL2/install/libdata/kgconfig"
          PKG_CONFIG_LIBDIR: "${{ github.workspace }}/vendor/SDL2/install/libdata/pkgconfig"
          PKG_CONFIG_SYSROOT_DIR: "/"
          PKG_CONFIG_ALLOW_SYSTEM_LIBS: "1"
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_SYSTEM_NAME=FreeBSD \
            -DCMAKE_SYSTEM_VERSION="14.0" \
            -DCMAKE_AR="${{ github.workspace }}/artifacts/zig-ar" \
            -DCMAKE_RANLIB="${{ github.workspace }}/artifacts/zig-ranlib" \
            -DCMAKE_C_COMPILER_AR="${{ github.workspace }}/artifacts/zig-ar" \
            -DCMAKE_CXX_COMPILER_AR="${{ github.workspace }}/artifacts/zig-ar" \
            -DCMAKE_C_COMPILER_RANLIB="${{ github.workspace }}/artifacts/zig-ranlib" \
            -DCMAKE_CXX_COMPILER_RANLIB="${{ github.workspace }}/artifacts/zig-ranlib" \
            -DBACKEND=sdl2 \
            -DAUDIO_BACKEND=miniaudio \
            -DWERROR=ON \
            -DCMAKE_C_COMPILER_TARGET=${{ matrix.target_triple }} \
            -DCMAKE_CXX_COMPILER_TARGET=${{ matrix.target_triple }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/vendor/SDL2/install" \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build
